### ISSUE TITLE
Newly registered datacatalog Gouda Tijdmachine not crawled

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#252]
The datacatalog https://www.goudatijdmachine.nl/data/files/datacatalog.ttl validates (200) and when added to the Data Register a HTTP 202 is returned signaling the dataset will be added. Yet, the dataset isn't added. 

The logs show that fetch.js is unable the find any datasets in the provided datacatalog:

```
{"level":30,"time":1631480304524,"pid":17,"hostname":"registry-api-66dffc845d-ln8w7","reqId":"req-c","req":{"method":"POST","url":"/datasets","hostname":"datasetregister.netwerkdigitaalerfgoed.nl","remoteAddress":"10.244.0.54","remotePort":40976},"msg":"incoming request"}
{"level":30,"time":1631480304526,"pid":17,"hostname":"registry-api-66dffc845d-ln8w7","reqId":"req-c","msg":"https://www.goudatijdmachine.nl/data/files/datacatalog.ttl"}
{"level":30,"time":1631480304728,"pid":17,"hostname":"registry-api-66dffc845d-ln8w7","reqId":"req-c","res":{"statusCode":202},"responseTime":203.46511900424957,"msg":"request completed"}
{"level":50,"time":1631480304939,"pid":17,"hostname":"registry-api-66dffc845d-ln8w7","reqId":"req-c","err":{"type":"NoDatasetFoundAtUrl","message":"","stack":"Error\n    at fetch (/app/build/src/fetch.js:38:15)\n    at async Object.<anonymous> (/app/build/src/server.js:129:30)"},"msg":"Promise errored, but reply.sent = true was set"}

```

**Comment by ddeboer** [comment]
Have you tried to query the URL with Comunica?

**Comment by coret** [comment]
```
$ comunica-sparql https://www.goudatijdmachine.nl/data/files/datacatalog.ttl \
"CONSTRUCT WHERE { ?s a <https://schema.org/Dataset> } LIMIT 100"
<https://www.goudatijdmachine.nl/data/api/items/145> a <https://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/240> a <https://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/242> a <https://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/244> a <https://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/246> a <https://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/248> a <https://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/250> a <https://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/259> a <https://schema.org/Dataset>.
```
But the following query (based on [our code](https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/main/src/fetch.ts#L122)) doesn't give any results:
```
$ comunica-sparql https://www.goudatijdmachine.nl/data/files/datacatalog.ttl \
"CONSTRUCT WHERE { ?s a schema:Dataset } LIMIT 100"
```

**Comment by coret** [comment]
When I change the prefix definition of schema to http://schema.org/ (in my datasetdescriptionsfile, note different URL of ttl), then the query has results again:
```
$comunica-sparql https://www.goudatijdmachine.nl/data/files/datacatalog-test.ttl \ 
"CONSTRUCT WHERE { ?s a schema:Dataset } LIMIT 100"
<https://www.goudatijdmachine.nl/data/api/items/145> a <http://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/240> a <http://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/242> a <http://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/244> a <http://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/246> a <http://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/248> a <http://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/250> a <http://schema.org/Dataset>.
<https://www.goudatijdmachine.nl/data/api/items/259> a <http://schema.org/Dataset>.
```

BTW in [Requirements for Datasets](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/) we use https://schema.org/

So I guess Comunica is using its own definition of schema (http)?

**Comment by EnnoMeijers** [comment]
Might be a prefix problem http://schema.org instead of https://schema.org?

**Comment by coret** [comment]
Strangely, when I query the NOB datasetdescriptions, which use http**s**://schema.org/ (inline in https://data.spinque.com/ld/data/netwerkoorlogsbronnen/) then querying via Comunica for schema:Dataset is no problem:
```
$ comunica-sparql https://data.spinque.com/ld/data/netwerkoorlogsbronnen/ \
"CONSTRUCT WHERE { ?s a schema:Dataset } LIMIT 100"
<https://data.spinque.com/ld/data/netwerkoorlogsbronnen/archieven_niod/> a <http://schema.org/Dataset>.
<https://data.spinque.com/ld/data/netwerkoorlogsbronnen/beeldbank_bhic/> a <http://schema.org/Dataset>.
<https://data.spinque.com/ld/data/netwerkoorlogsbronnen/beeldbank_heusden/> a <http://schema.org/Dataset>.
<https://data.spinque.com/ld/data/netwerkoorlogsbronnen/archieven_zeeuwsarchief/> a <http://schema.org/Dataset>.
...
```

**Comment by coret** [comment]
Same issue with https://www.openarch.nl/ - in this case the datasetdescriptions which are already in the Dataset Register aren't updated because no datasets are found (without any signal - adds to priority of https://github.com/netwerk-digitaal-erfgoed/dataset-register/issues/112).

**Comment by ddeboer** [comment]
> the datasetdescriptions which are already in the Dataset Register aren't updated because no datasets are found

How did you reach that conclusion? [This query](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=Recent%20geregistreerde%20URL%E2%80%99s&infer=true&sameAs=true&query=PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0ASELECT%20%3Fstatus%20%3FdateRead%20FROM%0A%3Chttps%3A%2F%2Fdemo.netwerkdigitaalerfgoed.nl%2Fregistry%2Fregistrations%3E%0AWHERE%20%7B%20%0A%3Chttps%3A%2F%2Fwww.openarch.nl%2Fdatasets%2F%3E%20a%20schema%3AEntryPoint%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AdateRead%20%3FdateRead%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3Astatus%20%3Fstatus%20%0A%7D) shows us that the registration URL is valid and was read last night.

**Comment by coret** [comment]
In regards of the updates I must have been fooled by the browser cache.

**Comment by ddeboer** [comment]
The difference is in the serialisation format. While [our SHACL has `http://schema.org/`](https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/main/shacl/register.ttl#L2), JSON-LD works fine with both `http://schema.org/` and `https://schema.org/` due to how Comunica dereferences Schema.org when reading JSON-LD documents.

This is not the case for other serialisation forms, however, including the Turtle at https://www.goudatijdmachine.nl/data/files/datacatalog.ttl. The RDF doesn’t conform to your SHACL (e.g. multiple creators, dates that are strings and other issues). Still it is accepted by us when validating because our SHACL looks for `http://schema.org/` and the TTL is `https://schema.org/`.

I’m now looking for a way to support both HTTP and HTTPS, as recommended by [recommended by Schema.org](https://schema.org/docs/faq.html#19).

**Comment by coret** [comment]
In regard to the multiple creators I added https://github.com/netwerk-digitaal-erfgoed/requirements-datasets/issues/48 (because in this case two organisations are creator, it's no mistake in the data, but invalid with our current SHACL). The dates now have the correct types.

Our SHACL now has `@prefix schema: <http://schema.org/> .`  and the examples in our requirements uses https://schema.org/
Although schema.org recommends support for both, shouldn't we be more consistent here (besides the mapping you suggested)?

**Comment by ddeboer** [comment]
See also https://github.com/netwerk-digitaal-erfgoed/dataset-register/pull/96.
